### ISSUE TITLE
Could not invoke IntercomWrapper.updateUser

### ISSUE THREAD

**Issue by agrass** [tinycreative/react-native-intercom#123]
Hi, 
I'm with a problem with Android and RN 41. When I call the Intercom.updateUser I get this error:  ``Could not invoke IntercomWrapper.updateUser`` anyone know what could be wrong?? The function registerIdentifiedUser is working

**Comment by agrass** [comment]
fixed using the call back instead this: 
```
Intercom.registerIdentifiedUser({data});
Intercom.updateUser({data});
```
like this is working: 
```
Intercom.registerIdentifiedUser({data}}, () => {
            Intercom.updateUser({data});
          });

```

**Comment by agrass** [comment]
Still some times I get this error: 
```
java.lang.RuntimeException: Could not invoke IntercomWrapper.updateUser
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:333)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	... 8 more
08-28 10:41:30.418  7447  7520 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method updateUser(Ljava/util/Map;)V in class Lio/intercom/android/sdk/Intercom; or its super classes (declaration of 'io.intercom.android.sdk.Intercom' appears in /data/app/dsappp/base.apk)
08-28 10:41:30.418  7447  7520 E AndroidRuntime: 	at com.robinpowered.react.Intercom.IntercomModule.updateUser(IntercomModule.java:92)
```

**Comment by Kottidev** [comment]
I have the same error ?

**Comment by rogchap** [comment]
Seems the `updateUser(Map<String, ?> attributes)` has be deprecated a while ago:
https://github.com/intercom/intercom-android/issues/315

**Comment by Kottidev** [comment]
Thanks

**Comment by Kottidev** [comment]
I create new PR , 
https://github.com/tinycreative/react-native-intercom/pull/132
