### ISSUE TITLE
java.lang.NoClassDefFoundError: io.intercom.com.google.gson.Gson on Android 4.4.2 

### ISSUE THREAD

**Issue by pi-sw** [tinycreative/react-native-intercom#127]
I encounter following error on app start:

```
java.lang.NoClassDefFoundError: io.intercom.com.google.gson.Gson
at io.intercom.android.sdk.metrics.MetricsStore.<init>(MetricsStore.java:41)
at io.intercom.android.sdk.metrics.MetricsStore.<init>(MetricsStore.java:48)
at io.intercom.android.sdk.Injector.getMetricsStore(Injector.java:187)
at io.intercom.android.sdk.Injector.getLifecycleTracker(Injector.java:231)
at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:93)
at io.intercom.android.sdk.RealIntercom.create(RealIntercom.java:70)
at io.intercom.android.sdk.Intercom.initialize(Intercom.java:72)
at com.troutloud.dvel.MainApplication.onCreate(MainApplication.java:83)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
at android.app.ActivityThread.access$1600(ActivityThread.java:175)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ghost** [comment]
+1
I have the same issue Android 4.4.4

**Comment by PhuongDinovative** [comment]
Me too Android 4.4.4

**Comment by ahulyk** [comment]
Got that issue on Android  4.2.2, Galaxy Ace3
https://pastebin.com/L2SyYPtN
Please fix it

**Comment by DrJid** [comment]
Did anyone figure out a solution for this?

**Comment by DrJid** [comment]
Looked into this some more. This crash was only occurring on Android < 5.0 probably because you've enabled multidex but haven't completed the other steps needed for Android < 5.0. Followed these steps over here and it worked great for me. 

https://developer.android.com/studio/build/multidex
