### ISSUE TITLE
Jest Snapshots tests fails due to sdk 

### ISSUE THREAD

**Issue by isAlmogK** [tinycreative/react-native-intercom#168]
So I'm creating Jest Snapshots tests on my components, and I'm getting the following fail error due to IntercomClient 

 RUNS  app/components/photos/__tests__/_AddCommentComponent.spec.js
 FAIL  app/components/photos/__tests__/_AddCommentComponent.spec.js

 RUNS  app/components/photos/__tests__/_AddCommentComponent.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'UNREAD_CHANGE_NOTIFICATION' of undefined
      
      at new IntercomClient (node_modules/react-native-intercom/lib/IntercomClient.js:26:117)
      at Object.<anonymous> (node_modules/react-native-intercom/lib/IntercomClient.js:356:16)
      at Object.<anonymous> (app/lib/helpers/intercomHelpers.js:5:197)
      at Object.<anonymous> (app/components/photos/AddComment.js:7:23)

Does anyone have any ideas?

**Comment by isAlmogK** [comment]
OK was able to fix this by adding jest.mock('react-native-intercom', () => 'Intercom')
