### ISSUE TITLE
Android: Unable to get provider io.intercom.android.sdk.IntercomInitializeContentProvider

### ISSUE THREAD

**Issue by TareqElMasriDev** [tinycreative/react-native-intercom#210]
I'm currently having an issue with my android build for 4.0.1+, strangely it happens only with android versions 4.X, that means it doesn't occur and works fine with Android 5 ~ 8

React-Native: 0.55.4
Android Version: 4.3
targetSdkVersion 27
Intercom Version: 5

My build.gradle:
```
    compile project(':react-native-intercom')
    compile 'io.intercom.android:intercom-sdk-base:5.+'
    compile 'io.intercom.android:intercom-sdk-fcm:5.+'
    compile 'com.google.firebase:firebase-core:11.+'
    compile 'com.google.firebase:firebase-messaging:11.+'
```

That's the log I'm having
```
E/AndroidRuntime( 6467): java.lang.RuntimeException: Unable to get provider io.intercom.android.sdk.IntercomInitializeContentProvider: java.lang.ClassNotFoundException: Didn't find class "io.intercom.android.sdk.IntercomInitializeContentProvider" on path: DexPathList[[zip file "/data/app/com.harmonika-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.harmonika-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5004)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4607)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4547)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.access$1300(ActivityThread.java:150)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
E/AndroidRuntime( 6467): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6467): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.main(ActivityThread.java:5225)
E/AndroidRuntime( 6467): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6467): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 6467): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
E/AndroidRuntime( 6467): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime( 6467): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 6467): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.intercom.android.sdk.IntercomInitializeContentProvider" on path: DexPathList[[zip file "/data/app/com.harmonika-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.harmonika-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 6467): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
E/AndroidRuntime( 6467): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime( 6467): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime( 6467): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4989)
E/AndroidRuntime( 6467): 	... 12 more
```

**Comment by TareqElMasriDev** [comment]
I fixed it, by using MultiDex

build.gradle
```
    compile 'com.android.support:multidex:1.0.1'
```

MainApplication.java
```
import android.content.Context;
import android.support.multidex.MultiDex;

public class MainApplication extends Application implements ReactApplication {
  ...
  @Override
  protected void attachBaseContext(Context context) {
    super.attachBaseContext(context);
    MultiDex.install(this);
  }
}
```

**Comment by HaseebWarriach** [comment]
But ihn this scenerio when you have two application activities(exteneded by Application),how you handled them both in the manifest.xml file?
