### ISSUE TITLE
Not receiving Push Notifications when an app is closed

### ISSUE THREAD

**Issue by viscoze** [tinycreative/react-native-intercom#270]
Hi there 👋 
We've got a problem with receiving pushes when an app is closed. It works well when the app is open and backgrounded. When it's closed we using `logcat` we found out that a message is received, but it can't be displayed as a push because of low priority.

How can it be fixed?

Warning message:
`Background messages will only work if the message priority is set to 'high'`

The whole log:
```
02-16 14:53:07.067 27388 27461 D RNFMessagingService: onMessageReceived event received
02-16 14:53:07.076  1818  3922 D CompatibilityInfo: mCompatibilityFlags - 0
02-16 14:53:07.076  1818  3922 D CompatibilityInfo: applicationDensity - 480
02-16 14:53:07.076  1818  3922 D CompatibilityInfo: applicationScale - 1.0
02-16 14:52:57.675  1818  2137 E UsbDeviceManager: handle message = 9
02-16 14:53:07.079  1818  6744 W ActivityManager: Background start not allowed: service Intent { cmp=com.killi_app.debug/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) } to com.killi_app.debug/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService from pid=27388 uid=10189 pkg=com.killi_app.debug startFg?=false
02-16 14:53:07.084 27388 27461 E RNFMessagingService: Background messages will only work if the message priority is set to 'high'
02-16 14:53:07.084 27388 27461 E RNFMessagingService: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.killi_app.debug/io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService (has extras) }: app is in background uid UidRecord{1dd459d u0a189 RCVR idle change:uncached procs:1 seq(0,0,0)}
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at android.app.ContextImpl.startService(ContextImpl.java:1532)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at android.content.ContextWrapper.startService(ContextWrapper.java:664)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at io.invertase.firebase.messaging.RNFirebaseMessagingService.onMessageReceived(RNFirebaseMessagingService.java:51)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at com.google.firebase.iid.zzg.run(Unknown Source:4)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
02-16 14:53:07.084 27388 27461 E RNFMessagingService:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by matthewng** [comment]
Was there a solution to this issue? It is happening for me as well.

**Comment by atrofimenko** [comment]
Hello! Faced with a same issue, it's happening for me too^ do you have any suggestions?
