### ISSUE TITLE
Execution failed for task ':intercom_intercom-react-native:verifyReleaseResources'

### ISSUE THREAD

**Issue by taylorjosephgriffin** [tinycreative/react-native-intercom#471]
```
    "react": "18.1.0",
    "react-native": "0.70.6",
    "@intercom/intercom-react-native": "^1.1.1",
```

```> Task :intercom_intercom-react-native:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':intercom_intercom-react-native:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/PATH_TO_NODE_MODULES/@intercom/intercom-react-native/android/build/intermediates/merged_res/release/values/values.xml:7268: AAPT: error: resource android:attr/lStar not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 2m 34s
1523 actionable tasks: 8 executed, 1515 up-to-date
error Failed to build the app.
Error: Command failed: ./gradlew build -x lint
    at makeError (/PATH_TO_NODE_MODULES/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/PATH_TO_NODE_MODULES/node_modules/execa/index.js:338:15)
    at buildApk (/PATH_TO_NODE_MODULES/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:141:22)
    at runOnSpecificDevice (/PATH_TO_NODE_MODULES/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:122:7)
    at buildAndRun (/PATH_TO_NODE_MODULES/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:107:12)
    at /PATH_TO_NODE_MODULES/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:96:12
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.handleAction (/PATH_TO_NODE_MODULES/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by taylorjosephgriffin** [comment]
sorry wrong package
